### ISSUE TITLE
Remove Defunct Place Page

### ISSUE THREAD

**Issue by fzohra** [keerthanakumar/cs373-idb#103]
The visceral Place page is confusing users. Need to remove this.

**Comment by ncrum** [comment]
what is this referring to?

**Comment by fzohra** [comment]
the Place page in home/about us/places/map/test.

**Comment by ncrum** [comment]
Could you elaborate on exactly what you're referring to? I don't know of a place page on all those routes

**Comment by fzohra** [comment]
The 'Places' in the nav bar on the top of the site

**Comment by ncrum** [comment]
So to recreate this:
1. Click on `Places` tab without specifying a phrase/type
2. `Places` tab opens and displays no results, which is weird.

Is that right?

**Comment by fzohra** [comment]
yeah

**Comment by ncrum** [comment]
Then we should just redirect to home page if no results are returned by the api call
