### ISSUE TITLE
Redesign the UI

### ISSUE THREAD

**Issue by fzohra** [keerthanakumar/cs373-idb#105]
User feedback on the UI is very negative. People do not understand the filter buttons. Text is un-aesthetically large.

**Comment by ncrum** [comment]
We could change 'Filters' to 'Categories'? Also we could change the circles to buttons underneath the search bar. Also which text is this referring to?

**Comment by fzohra** [comment]
The text in the results for the list of places.

**Comment by ncrum** [comment]
That's fair, we do need to redesign the places page to display results better

**Comment by fzohra** [comment]
I like how we have things, but I've been getting feedback from other students about it and they seem very confused about how to navigate and use our site.

**Comment by fzohra** [comment]
thats why I think we need to redesign some things

**Comment by ncrum** [comment]
@fzohra @YunJang @keerthanakumar @safaaleigh I think a good idea would be if everyone could post a comment in here with a UI change they think would help.

**Comment by ncrum** [comment]
Checklist for redesign:
* [x] Home Page
* [ ] About Page
* [x] Places Page
* [x] Map Page
* [ ] Details Page
* [ ] Reviews Page (minor change, could use further updating)
* [x] Test Page (pre-checking this since it should be fine)
