### ISSUE TITLE
Photos for Places have too many Repeats

### ISSUE THREAD

**Issue by fzohra** [keerthanakumar/cs373-idb#106]
the photo slider shows too many circle. Make it display a circle for each unique photo.

**Comment by ncrum** [comment]
Which problem is this:
1. Duplicates are being given as a result of the backend api call
or
2. Duplicates are a result of the frontend code having a bug

If this is (1), then that's a hard issue to fix, unless the links are identical. If the photos are just similar, then  we can't really do much.

**Comment by fzohra** [comment]
It's 2. It was fine before when I looked at it, but some change yesterday seemed to have triggered multiple photos being displayed.
