### ISSUE TITLE
remove circle buttons on test page and replace with normal buttons

### ISSUE THREAD

**Issue by ncrum** [keerthanakumar/cs373-idb#115]

**Comment by fzohra** [comment]
Here are two options:
![image](https://cloud.githubusercontent.com/assets/5297276/7284450/38181e6e-e903-11e4-8d03-4816b3616f07.png)

![image](https://cloud.githubusercontent.com/assets/5297276/7284586/62920d3e-e904-11e4-9068-4c9d523c57db.png)

I like the second one better. Opinions?

**Comment by ncrum** [comment]
definitely the second!
