### ISSUE TITLE
Create tests.py for three unit tests on every 'Flask model' call

### ISSUE THREAD

**Issue by ncrum** [keerthanakumar/cs373-idb#52]
See from Downing's spec:
"6. Write unit tests in tests.py that test corner cases and failure cases until you have an average of 3 tests for each __Flask model__ call, confirm the expected failures, and add, commit, and push to the public code repo."

**Comment by fzohra** [comment]
added functional tests. trying to resolve db session issues to have model tests too

**Comment by fzohra** [comment]
added unittests for models too
