### ISSUE TITLE
unit test AssertionError

### ISSUE THREAD

**Issue by ncrum** [keerthanakumar/cs373-idb#67]
Traceback (most recent call last):
  File "tests.py", line 236, in test_Review_to_dict
    self.assertEqual(a.to_dict(), e)
AssertionError: {'aut[31 chars]com/106065191029323132178', 'place_id': 689, '[69 chars]1839} != {'aut[31 chars]com/114392659892412999560', 'place_id': 689, '[271 chars]1839}
- {'author_name': 'Lily Watson',
-  'author_url': 'https://plus.google.com/106065191029323132178',
+ {'author_name': 'Sarah Chappell',
+  'author_url': 'https://plus.google.com/114392659892412999560',
   'place_id': 689,
   'rating': 5.0,
   'review_id': 1839,
-  'text': ''}
+  'text': 'Best darn swimming hole in Austin!  We love taking the kids here '
+          'and just enjoying a hot summer day swimming in the ice cold '
+          'water.  They kids love the diving board and the shallow play area '
+          'as well.'}

----------------------------------------------------------------------
Ran 19 tests in 59.587s

**Comment by ncrum** [comment]
@fzohra 
coverage commands
% coverage3 run --branch TestNetflix.py >  TestNetflix.out 2>&1
% coverage3 report -m                   >> TestNetflix.out

**Comment by fzohra** [comment]
thanks!

**Comment by fzohra** [comment]
tests fixed. working on coverage

**Comment by fzohra** [comment]
the coverage report makes no sense o_o
