### ISSUE TITLE
add more records for food places (using radius/distance queries?)

### ISSUE THREAD

**Issue by ncrum** [keerthanakumar/cs373-idb#76]

**Comment by YunJang** [comment]
Do we want to type/radius search to just work for food or do you mean we just need to get more records for the food section?

**Comment by fzohra** [comment]
We need to get more records for mainly the food/drink types

**Comment by YunJang** [comment]
Okay, got it.

**Comment by YunJang** [comment]
Forgot to close this in commit SHA: ec86ca0cba5b124cac699de2a6f99dc3105aec75.
